// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaign_time.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCampaignTime = `-- name: GetCampaignTime :one
SELECT campaign_id, day, hour, minute, updated_at
FROM campaign_time
WHERE campaign_id = $1
`

func (q *Queries) GetCampaignTime(ctx context.Context, campaignID pgtype.UUID) (CampaignTime, error) {
	row := q.db.QueryRow(ctx, getCampaignTime, campaignID)
	var i CampaignTime
	err := row.Scan(
		&i.CampaignID,
		&i.Day,
		&i.Hour,
		&i.Minute,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCampaignTime = `-- name: UpsertCampaignTime :one
INSERT INTO campaign_time (campaign_id, day, hour, minute)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id) DO UPDATE
SET day = EXCLUDED.day, hour = EXCLUDED.hour, minute = EXCLUDED.minute, updated_at = now()
RETURNING campaign_id, day, hour, minute, updated_at
`

type UpsertCampaignTimeParams struct {
	CampaignID pgtype.UUID
	Day        int32
	Hour       int32
	Minute     int32
}

func (q *Queries) UpsertCampaignTime(ctx context.Context, arg UpsertCampaignTimeParams) (CampaignTime, error) {
	row := q.db.QueryRow(ctx, upsertCampaignTime,
		arg.CampaignID,
		arg.Day,
		arg.Hour,
		arg.Minute,
	)
	var i CampaignTime
	err := row.Scan(
		&i.CampaignID,
		&i.Day,
		&i.Hour,
		&i.Minute,
		&i.UpdatedAt,
	)
	return i, err
}
