// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: journal_entries.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO player_journal_entries (campaign_id, title, content)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, title, content, created_at, updated_at
`

type CreateJournalEntryParams struct {
	CampaignID pgtype.UUID
	Title      string
	Content    string
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (PlayerJournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry, arg.CampaignID, arg.Title, arg.Content)
	var i PlayerJournalEntry
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM player_journal_entries WHERE id = $1
`

func (q *Queries) DeleteJournalEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, id)
	return err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, campaign_id, title, content, created_at, updated_at
FROM player_journal_entries
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJournalEntries(ctx context.Context, campaignID pgtype.UUID) ([]PlayerJournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerJournalEntry
	for rows.Next() {
		var i PlayerJournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
