// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package statedb

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type BeliefSystem struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Name        string
	Details     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PlayerKnown bool
}

type Campaign struct {
	ID                  pgtype.UUID
	Name                string
	Description         pgtype.Text
	Genre               pgtype.Text
	Tone                pgtype.Text
	Themes              []string
	Status              string
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	WorldType           pgtype.Text
	DangerLevel         pgtype.Text
	PoliticalComplexity pgtype.Text
	RulesMode           string
}

type CampaignTime struct {
	CampaignID pgtype.UUID
	Day        int32
	Hour       int32
	Minute     int32
	UpdatedAt  pgtype.Timestamptz
}

type CharacterFeat struct {
	ID          pgtype.UUID
	CharacterID pgtype.UUID
	FeatID      pgtype.UUID
	GrantedAt   pgtype.Timestamptz
}

type CharacterSkill struct {
	ID          pgtype.UUID
	CharacterID pgtype.UUID
	SkillID     pgtype.UUID
	Points      int32
}

type Culture struct {
	ID             pgtype.UUID
	CampaignID     pgtype.UUID
	LanguageID     pgtype.UUID
	BeliefSystemID pgtype.UUID
	Name           string
	Details        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PlayerKnown    bool
}

type EconomicSystem struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Name        string
	Details     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PlayerKnown bool
}

type EntityRelationship struct {
	ID               pgtype.UUID
	CampaignID       pgtype.UUID
	SourceEntityType string
	SourceEntityID   pgtype.UUID
	TargetEntityType string
	TargetEntityID   pgtype.UUID
	RelationshipType string
	Description      pgtype.Text
	Strength         pgtype.Int4
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	PlayerAware      bool
}

type Faction struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Name        string
	Description pgtype.Text
	Agenda      pgtype.Text
	Territory   pgtype.Text
	Properties  []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type FactionRelationship struct {
	ID               pgtype.UUID
	FactionID        pgtype.UUID
	RelatedFactionID pgtype.UUID
	RelationshipType string
	Description      pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FeatDefinition struct {
	ID            pgtype.UUID
	CampaignID    pgtype.UUID
	Name          string
	Description   string
	Prerequisites string
	BonusType     string
	BonusValue    int32
	CreatedAt     pgtype.Timestamptz
}

type Item struct {
	ID                pgtype.UUID
	CampaignID        pgtype.UUID
	PlayerCharacterID pgtype.UUID
	Name              string
	Description       pgtype.Text
	ItemType          string
	Rarity            string
	Properties        []byte
	Equipped          bool
	Quantity          int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Language struct {
	ID                 pgtype.UUID
	CampaignID         pgtype.UUID
	Name               string
	Phonology          []byte
	Naming             []byte
	Vocabulary         []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SpokenByFactionIds []pgtype.UUID
	SpokenByCultureIds []pgtype.UUID
	Description        string
	PlayerKnown        bool
}

type Location struct {
	ID            pgtype.UUID
	CampaignID    pgtype.UUID
	Name          string
	Description   pgtype.Text
	Region        pgtype.Text
	LocationType  pgtype.Text
	Properties    []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PlayerVisited bool
	PlayerKnown   bool
}

type LocationConnection struct {
	ID             pgtype.UUID
	FromLocationID pgtype.UUID
	ToLocationID   pgtype.UUID
	Description    pgtype.Text
	Bidirectional  bool
	TravelTime     pgtype.Text
	CampaignID     pgtype.UUID
}

type Memory struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Content      string
	Embedding    pgvector_go.Vector
	MemoryType   string
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
	InGameTime   pgtype.Text
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

type Npc struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Name        string
	Description pgtype.Text
	Personality pgtype.Text
	Disposition int32
	LocationID  pgtype.UUID
	FactionID   pgtype.UUID
	Alive       bool
	Hp          pgtype.Int4
	Stats       []byte
	Properties  []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PlayerCharacter struct {
	ID                pgtype.UUID
	CampaignID        pgtype.UUID
	UserID            pgtype.UUID
	Name              string
	Description       pgtype.Text
	Stats             []byte
	Hp                int32
	MaxHp             int32
	Experience        int32
	Level             int32
	Status            string
	Abilities         []byte
	CurrentLocationID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PlayerJournalEntry struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
	Title      string
	Content    string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Quest struct {
	ID            pgtype.UUID
	CampaignID    pgtype.UUID
	ParentQuestID pgtype.UUID
	Title         string
	Description   pgtype.Text
	QuestType     string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type QuestHistory struct {
	ID        pgtype.UUID
	QuestID   pgtype.UUID
	Snapshot  string
	CreatedAt pgtype.Timestamptz
}

type QuestNote struct {
	ID        pgtype.UUID
	QuestID   pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type QuestObjective struct {
	ID          pgtype.UUID
	QuestID     pgtype.UUID
	Description string
	Completed   bool
	OrderIndex  int32
}

type SavePoint struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
	Name       string
	TurnNumber int32
	IsAuto     bool
	CreatedAt  pgtype.Timestamptz
}

type SessionLog struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	TurnNumber   int32
	PlayerInput  string
	InputType    string
	LlmResponse  string
	ToolCalls    []byte
	LocationID   pgtype.UUID
	NpcsInvolved []pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type SessionSummary struct {
	ID         pgtype.UUID
	CampaignID pgtype.UUID
	FromTurn   int32
	ToTurn     int32
	Summary    string
	CreatedAt  pgtype.Timestamptz
}

type SkillDefinition struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Name        string
	Description string
	BaseAbility string
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

type WorldFact struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Fact         string
	Category     string
	Source       string
	SupersededBy pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	PlayerKnown  bool
}
