// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: player_characters.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerCharacter = `-- name: CreatePlayerCharacter :one
INSERT INTO player_characters (
  campaign_id,
  user_id,
  name,
  description,
  stats,
  hp,
  max_hp,
  experience,
  level,
  status,
  abilities,
  current_location_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE($5::jsonb, '{}'::jsonb),
  $6,
  $7,
  $8,
  $9,
  $10,
  COALESCE($11::jsonb, '[]'::jsonb),
  $12
)
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type CreatePlayerCharacterParams struct {
	CampaignID        pgtype.UUID
	UserID            pgtype.UUID
	Name              string
	Description       pgtype.Text
	Stats             []byte
	Hp                int32
	MaxHp             int32
	Experience        int32
	Level             int32
	Status            string
	Abilities         []byte
	CurrentLocationID pgtype.UUID
}

func (q *Queries) CreatePlayerCharacter(ctx context.Context, arg CreatePlayerCharacterParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, createPlayerCharacter,
		arg.CampaignID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Stats,
		arg.Hp,
		arg.MaxHp,
		arg.Experience,
		arg.Level,
		arg.Status,
		arg.Abilities,
		arg.CurrentLocationID,
	)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerCharacterByCampaign = `-- name: GetPlayerCharacterByCampaign :many
SELECT id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
FROM player_characters
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) GetPlayerCharacterByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]PlayerCharacter, error) {
	rows, err := q.db.Query(ctx, getPlayerCharacterByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerCharacter
	for rows.Next() {
		var i PlayerCharacter
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Stats,
			&i.Hp,
			&i.MaxHp,
			&i.Experience,
			&i.Level,
			&i.Status,
			&i.Abilities,
			&i.CurrentLocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerCharacterByID = `-- name: GetPlayerCharacterByID :one
SELECT id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
FROM player_characters
WHERE id = $1
`

func (q *Queries) GetPlayerCharacterByID(ctx context.Context, id pgtype.UUID) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, getPlayerCharacterByID, id)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerAbilities = `-- name: UpdatePlayerAbilities :one
UPDATE player_characters
SET
  abilities = COALESCE($1::jsonb, '[]'::jsonb),
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerAbilitiesParams struct {
	Abilities []byte
	ID        pgtype.UUID
}

func (q *Queries) UpdatePlayerAbilities(ctx context.Context, arg UpdatePlayerAbilitiesParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerAbilities, arg.Abilities, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerCharacter = `-- name: UpdatePlayerCharacter :one
UPDATE player_characters
SET
  name = $1,
  description = $2,
  stats = COALESCE($3::jsonb, '{}'::jsonb),
  hp = $4,
  max_hp = $5,
  experience = $6,
  level = $7,
  status = $8,
  abilities = COALESCE($9::jsonb, '[]'::jsonb),
  current_location_id = $10,
  updated_at = now()
WHERE id = $11
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerCharacterParams struct {
	Name              string
	Description       pgtype.Text
	Stats             []byte
	Hp                int32
	MaxHp             int32
	Experience        int32
	Level             int32
	Status            string
	Abilities         []byte
	CurrentLocationID pgtype.UUID
	ID                pgtype.UUID
}

func (q *Queries) UpdatePlayerCharacter(ctx context.Context, arg UpdatePlayerCharacterParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerCharacter,
		arg.Name,
		arg.Description,
		arg.Stats,
		arg.Hp,
		arg.MaxHp,
		arg.Experience,
		arg.Level,
		arg.Status,
		arg.Abilities,
		arg.CurrentLocationID,
		arg.ID,
	)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerCurrentHP = `-- name: UpdatePlayerCurrentHP :one
UPDATE player_characters
SET
  hp = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerCurrentHPParams struct {
	Hp int32
	ID pgtype.UUID
}

func (q *Queries) UpdatePlayerCurrentHP(ctx context.Context, arg UpdatePlayerCurrentHPParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerCurrentHP, arg.Hp, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerExperience = `-- name: UpdatePlayerExperience :one
UPDATE player_characters
SET
  experience = $1,
  level = $2,
  updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerExperienceParams struct {
	Experience int32
	Level      int32
	ID         pgtype.UUID
}

func (q *Queries) UpdatePlayerExperience(ctx context.Context, arg UpdatePlayerExperienceParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerExperience, arg.Experience, arg.Level, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerHP = `-- name: UpdatePlayerHP :one
UPDATE player_characters
SET
  hp = $1,
  max_hp = $2,
  updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerHPParams struct {
	Hp    int32
	MaxHp int32
	ID    pgtype.UUID
}

func (q *Queries) UpdatePlayerHP(ctx context.Context, arg UpdatePlayerHPParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerHP, arg.Hp, arg.MaxHp, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerLevel = `-- name: UpdatePlayerLevel :one
UPDATE player_characters
SET
  level = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerLevelParams struct {
	Level int32
	ID    pgtype.UUID
}

func (q *Queries) UpdatePlayerLevel(ctx context.Context, arg UpdatePlayerLevelParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerLevel, arg.Level, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerLocation = `-- name: UpdatePlayerLocation :one
UPDATE player_characters
SET
  current_location_id = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerLocationParams struct {
	CurrentLocationID pgtype.UUID
	ID                pgtype.UUID
}

func (q *Queries) UpdatePlayerLocation(ctx context.Context, arg UpdatePlayerLocationParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerLocation, arg.CurrentLocationID, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerStats = `-- name: UpdatePlayerStats :one
UPDATE player_characters
SET
  stats = COALESCE($1::jsonb, '{}'::jsonb),
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerStatsParams struct {
	Stats []byte
	ID    pgtype.UUID
}

func (q *Queries) UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerStats, arg.Stats, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerStatus = `-- name: UpdatePlayerStatus :one
UPDATE player_characters
SET
  status = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, campaign_id, user_id, name, description, stats, hp, max_hp, experience, level, status, abilities, current_location_id, created_at, updated_at
`

type UpdatePlayerStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (PlayerCharacter, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatus, arg.Status, arg.ID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Stats,
		&i.Hp,
		&i.MaxHp,
		&i.Experience,
		&i.Level,
		&i.Status,
		&i.Abilities,
		&i.CurrentLocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
