// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteObjective(ctx context.Context, id pgtype.UUID) (QuestObjective, error)
	CreateBeliefSystem(ctx context.Context, arg CreateBeliefSystemParams) (BeliefSystem, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (LocationConnection, error)
	CreateCulture(ctx context.Context, arg CreateCultureParams) (Culture, error)
	CreateEconomicSystem(ctx context.Context, arg CreateEconomicSystemParams) (EconomicSystem, error)
	CreateFact(ctx context.Context, arg CreateFactParams) (WorldFact, error)
	CreateFaction(ctx context.Context, arg CreateFactionParams) (Faction, error)
	CreateFactionRelationship(ctx context.Context, arg CreateFactionRelationshipParams) (FactionRelationship, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (PlayerJournalEntry, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateNPC(ctx context.Context, arg CreateNPCParams) (Npc, error)
	CreateObjective(ctx context.Context, arg CreateObjectiveParams) (QuestObjective, error)
	CreatePlayerCharacter(ctx context.Context, arg CreatePlayerCharacterParams) (PlayerCharacter, error)
	CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error)
	CreateQuestHistoryEntry(ctx context.Context, arg CreateQuestHistoryEntryParams) (QuestHistory, error)
	CreateQuestNote(ctx context.Context, arg CreateQuestNoteParams) (QuestNote, error)
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (EntityRelationship, error)
	CreateSavePoint(ctx context.Context, arg CreateSavePointParams) (SavePoint, error)
	CreateSessionLog(ctx context.Context, arg CreateSessionLogParams) (SessionLog, error)
	CreateSessionSummary(ctx context.Context, arg CreateSessionSummaryParams) (SessionSummary, error)
	CreateUser(ctx context.Context, name string) (User, error)
	CreateUserWithAuth(ctx context.Context, arg CreateUserWithAuthParams) (CreateUserWithAuthRow, error)
	DeleteBeliefSystem(ctx context.Context, id pgtype.UUID) error
	DeleteCampaign(ctx context.Context, id pgtype.UUID) error
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error
	DeleteCulture(ctx context.Context, id pgtype.UUID) error
	DeleteEconomicSystem(ctx context.Context, id pgtype.UUID) error
	DeleteItem(ctx context.Context, id pgtype.UUID) error
	DeleteJournalEntry(ctx context.Context, id pgtype.UUID) error
	DeleteLanguage(ctx context.Context, id pgtype.UUID) error
	DeleteOldAutoSaves(ctx context.Context, campaignID pgtype.UUID) error
	DeleteQuestNote(ctx context.Context, arg DeleteQuestNoteParams) error
	DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error
	DeleteSavePoint(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetBeliefSystemByCulture(ctx context.Context, cultureID pgtype.UUID) (BeliefSystem, error)
	GetBeliefSystemByID(ctx context.Context, id pgtype.UUID) (BeliefSystem, error)
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignTime(ctx context.Context, campaignID pgtype.UUID) (CampaignTime, error)
	GetConnectionsFromLocation(ctx context.Context, arg GetConnectionsFromLocationParams) ([]GetConnectionsFromLocationRow, error)
	GetCultureByID(ctx context.Context, id pgtype.UUID) (Culture, error)
	GetEconomicSystemByID(ctx context.Context, id pgtype.UUID) (EconomicSystem, error)
	GetFactByID(ctx context.Context, id pgtype.UUID) (WorldFact, error)
	GetFactPlayerKnown(ctx context.Context, id pgtype.UUID) (bool, error)
	GetFactionByID(ctx context.Context, id pgtype.UUID) (Faction, error)
	GetFactionRelationships(ctx context.Context, factionID pgtype.UUID) ([]FactionRelationship, error)
	GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error)
	GetLanguageByID(ctx context.Context, id pgtype.UUID) (Language, error)
	GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error)
	GetMemoryByID(ctx context.Context, id pgtype.UUID) (Memory, error)
	GetNPCByID(ctx context.Context, arg GetNPCByIDParams) (Npc, error)
	GetPlayerCharacterByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]PlayerCharacter, error)
	GetPlayerCharacterByID(ctx context.Context, id pgtype.UUID) (PlayerCharacter, error)
	GetQuestByID(ctx context.Context, arg GetQuestByIDParams) (Quest, error)
	GetRelationshipsBetween(ctx context.Context, arg GetRelationshipsBetweenParams) ([]EntityRelationship, error)
	GetRelationshipsByEntity(ctx context.Context, arg GetRelationshipsByEntityParams) ([]EntityRelationship, error)
	GetSessionLogByID(ctx context.Context, id pgtype.UUID) (SessionLog, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	KillNPC(ctx context.Context, id pgtype.UUID) (Npc, error)
	ListActiveFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error)
	ListActiveQuests(ctx context.Context, campaignID pgtype.UUID) ([]Quest, error)
	ListAliveNPCsByLocation(ctx context.Context, arg ListAliveNPCsByLocationParams) ([]Npc, error)
	ListBeliefSystemsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]BeliefSystem, error)
	ListCampaignsByUser(ctx context.Context, createdBy pgtype.UUID) ([]Campaign, error)
	ListCulturesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Culture, error)
	ListCulturesByLanguage(ctx context.Context, languageID pgtype.UUID) ([]Culture, error)
	ListEconomicSystemsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]EconomicSystem, error)
	ListFactionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Faction, error)
	ListFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error)
	ListFactsByCategory(ctx context.Context, arg ListFactsByCategoryParams) ([]WorldFact, error)
	ListItemsByPlayer(ctx context.Context, arg ListItemsByPlayerParams) ([]Item, error)
	ListItemsByType(ctx context.Context, arg ListItemsByTypeParams) ([]Item, error)
	ListJournalEntries(ctx context.Context, campaignID pgtype.UUID) ([]PlayerJournalEntry, error)
	ListLanguagesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Language, error)
	ListLanguagesByFaction(ctx context.Context, factionID pgtype.UUID) ([]Language, error)
	ListLocationsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Location, error)
	ListLocationsByRegion(ctx context.Context, arg ListLocationsByRegionParams) ([]Location, error)
	ListMemoriesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Memory, error)
	ListNPCsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Npc, error)
	ListNPCsByFaction(ctx context.Context, arg ListNPCsByFactionParams) ([]Npc, error)
	ListNPCsByLocation(ctx context.Context, arg ListNPCsByLocationParams) ([]Npc, error)
	ListObjectivesByQuest(ctx context.Context, questID pgtype.UUID) ([]QuestObjective, error)
	ListObjectivesByQuests(ctx context.Context, questIds []pgtype.UUID) ([]QuestObjective, error)
	ListPlayerAwareRelationships(ctx context.Context, campaignID pgtype.UUID) ([]EntityRelationship, error)
	ListPlayerKnownBeliefSystems(ctx context.Context, campaignID pgtype.UUID) ([]BeliefSystem, error)
	ListPlayerKnownCultures(ctx context.Context, campaignID pgtype.UUID) ([]Culture, error)
	ListPlayerKnownEconomicSystems(ctx context.Context, campaignID pgtype.UUID) ([]EconomicSystem, error)
	ListPlayerKnownFacts(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error)
	ListPlayerKnownLanguages(ctx context.Context, campaignID pgtype.UUID) ([]Language, error)
	ListPlayerKnownLocations(ctx context.Context, campaignID pgtype.UUID) ([]Location, error)
	ListPlayerVisitedLocations(ctx context.Context, campaignID pgtype.UUID) ([]Location, error)
	ListQuestHistory(ctx context.Context, questID pgtype.UUID) ([]QuestHistory, error)
	ListQuestNotes(ctx context.Context, questID pgtype.UUID) ([]QuestNote, error)
	ListQuestsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Quest, error)
	ListQuestsByType(ctx context.Context, arg ListQuestsByTypeParams) ([]Quest, error)
	ListRecentSessionLogs(ctx context.Context, arg ListRecentSessionLogsParams) ([]SessionLog, error)
	ListRelationshipsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]EntityRelationship, error)
	ListSavePointsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]SavePoint, error)
	ListSessionLogsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]SessionLog, error)
	ListSessionLogsByLocation(ctx context.Context, arg ListSessionLogsByLocationParams) ([]SessionLog, error)
	ListSessionSummaries(ctx context.Context, campaignID pgtype.UUID) ([]SessionSummary, error)
	ListSubquestsByParentQuest(ctx context.Context, parentQuestID pgtype.UUID) ([]Quest, error)
	ListUsers(ctx context.Context) ([]User, error)
	Ping(ctx context.Context) (int32, error)
	SearchMemoriesBySimilarity(ctx context.Context, arg SearchMemoriesBySimilarityParams) ([]SearchMemoriesBySimilarityRow, error)
	SearchMemoriesWithFilters(ctx context.Context, arg SearchMemoriesWithFiltersParams) ([]SearchMemoriesWithFiltersRow, error)
	SetBeliefSystemPlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetCulturePlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetEconomicSystemPlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetFactPlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetLanguagePlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetLocationPlayerKnown(ctx context.Context, id pgtype.UUID) error
	SetLocationPlayerVisited(ctx context.Context, id pgtype.UUID) error
	SetRelationshipPlayerAware(ctx context.Context, id pgtype.UUID) error
	SupersedeFact(ctx context.Context, arg SupersedeFactParams) (WorldFact, error)
	TransferItem(ctx context.Context, arg TransferItemParams) (Item, error)
	UpdateBeliefSystem(ctx context.Context, arg UpdateBeliefSystemParams) (BeliefSystem, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateCulture(ctx context.Context, arg UpdateCultureParams) (Culture, error)
	UpdateEconomicSystem(ctx context.Context, arg UpdateEconomicSystemParams) (EconomicSystem, error)
	UpdateFaction(ctx context.Context, arg UpdateFactionParams) (Faction, error)
	UpdateFactionRelationship(ctx context.Context, arg UpdateFactionRelationshipParams) (FactionRelationship, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateItemEquipped(ctx context.Context, arg UpdateItemEquippedParams) (Item, error)
	UpdateItemProperties(ctx context.Context, arg UpdateItemPropertiesParams) (Item, error)
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error)
	UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateNPC(ctx context.Context, arg UpdateNPCParams) (Npc, error)
	UpdateNPCDisposition(ctx context.Context, arg UpdateNPCDispositionParams) (Npc, error)
	UpdateNPCLocation(ctx context.Context, arg UpdateNPCLocationParams) (Npc, error)
	UpdateObjective(ctx context.Context, arg UpdateObjectiveParams) (QuestObjective, error)
	UpdatePlayerAbilities(ctx context.Context, arg UpdatePlayerAbilitiesParams) (PlayerCharacter, error)
	UpdatePlayerCharacter(ctx context.Context, arg UpdatePlayerCharacterParams) (PlayerCharacter, error)
	UpdatePlayerCurrentHP(ctx context.Context, arg UpdatePlayerCurrentHPParams) (PlayerCharacter, error)
	UpdatePlayerExperience(ctx context.Context, arg UpdatePlayerExperienceParams) (PlayerCharacter, error)
	UpdatePlayerHP(ctx context.Context, arg UpdatePlayerHPParams) (PlayerCharacter, error)
	UpdatePlayerLevel(ctx context.Context, arg UpdatePlayerLevelParams) (PlayerCharacter, error)
	UpdatePlayerLocation(ctx context.Context, arg UpdatePlayerLocationParams) (PlayerCharacter, error)
	UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerCharacter, error)
	UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (PlayerCharacter, error)
	UpdateQuest(ctx context.Context, arg UpdateQuestParams) (Quest, error)
	UpdateQuestStatus(ctx context.Context, arg UpdateQuestStatusParams) (Quest, error)
	UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (EntityRelationship, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertCampaignTime(ctx context.Context, arg UpsertCampaignTimeParams) (CampaignTime, error)
}

var _ Querier = (*Queries)(nil)
