// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_points.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavePoint = `-- name: CreateSavePoint :one
INSERT INTO save_points (campaign_id, name, turn_number, is_auto)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, name, turn_number, is_auto, created_at
`

type CreateSavePointParams struct {
	CampaignID pgtype.UUID
	Name       string
	TurnNumber int32
	IsAuto     bool
}

func (q *Queries) CreateSavePoint(ctx context.Context, arg CreateSavePointParams) (SavePoint, error) {
	row := q.db.QueryRow(ctx, createSavePoint,
		arg.CampaignID,
		arg.Name,
		arg.TurnNumber,
		arg.IsAuto,
	)
	var i SavePoint
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.TurnNumber,
		&i.IsAuto,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAutoSaves = `-- name: DeleteOldAutoSaves :exec
DELETE FROM save_points AS sp
WHERE sp.campaign_id = $1
  AND sp.is_auto = true
  AND sp.id NOT IN (
    SELECT keep.id FROM save_points AS keep
    WHERE keep.campaign_id = $1 AND keep.is_auto = true
    ORDER BY keep.created_at DESC
    LIMIT 3
  )
`

func (q *Queries) DeleteOldAutoSaves(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOldAutoSaves, campaignID)
	return err
}

const deleteSavePoint = `-- name: DeleteSavePoint :exec
DELETE FROM save_points WHERE id = $1
`

func (q *Queries) DeleteSavePoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSavePoint, id)
	return err
}

const listSavePointsByCampaign = `-- name: ListSavePointsByCampaign :many
SELECT id, campaign_id, name, turn_number, is_auto, created_at
FROM save_points
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSavePointsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]SavePoint, error) {
	rows, err := q.db.Query(ctx, listSavePointsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavePoint
	for rows.Next() {
		var i SavePoint
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.TurnNumber,
			&i.IsAuto,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
