// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_summaries.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionSummary = `-- name: CreateSessionSummary :one
INSERT INTO session_summaries (campaign_id, from_turn, to_turn, summary)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, from_turn, to_turn, summary, created_at
`

type CreateSessionSummaryParams struct {
	CampaignID pgtype.UUID
	FromTurn   int32
	ToTurn     int32
	Summary    string
}

func (q *Queries) CreateSessionSummary(ctx context.Context, arg CreateSessionSummaryParams) (SessionSummary, error) {
	row := q.db.QueryRow(ctx, createSessionSummary,
		arg.CampaignID,
		arg.FromTurn,
		arg.ToTurn,
		arg.Summary,
	)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.FromTurn,
		&i.ToTurn,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionSummaries = `-- name: ListSessionSummaries :many
SELECT id, campaign_id, from_turn, to_turn, summary, created_at
FROM session_summaries
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionSummaries(ctx context.Context, campaignID pgtype.UUID) ([]SessionSummary, error) {
	rows, err := q.db.Query(ctx, listSessionSummaries, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSummary
	for rows.Next() {
		var i SessionSummary
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.FromTurn,
			&i.ToTurn,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
