// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: world_facts.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFact = `-- name: CreateFact :one
INSERT INTO world_facts (
  campaign_id,
  fact,
  category,
  source,
  player_known
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, campaign_id, fact, category, source, superseded_by, created_at, player_known
`

type CreateFactParams struct {
	CampaignID  pgtype.UUID
	Fact        string
	Category    string
	Source      string
	PlayerKnown bool
}

func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (WorldFact, error) {
	row := q.db.QueryRow(ctx, createFact,
		arg.CampaignID,
		arg.Fact,
		arg.Category,
		arg.Source,
		arg.PlayerKnown,
	)
	var i WorldFact
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.PlayerKnown,
	)
	return i, err
}

const getFactByID = `-- name: GetFactByID :one
SELECT id, campaign_id, fact, category, source, superseded_by, created_at, player_known
FROM world_facts
WHERE id = $1
`

func (q *Queries) GetFactByID(ctx context.Context, id pgtype.UUID) (WorldFact, error) {
	row := q.db.QueryRow(ctx, getFactByID, id)
	var i WorldFact
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.PlayerKnown,
	)
	return i, err
}

const getFactPlayerKnown = `-- name: GetFactPlayerKnown :one
SELECT player_known
FROM world_facts
WHERE id = $1
`

func (q *Queries) GetFactPlayerKnown(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getFactPlayerKnown, id)
	var player_known bool
	err := row.Scan(&player_known)
	return player_known, err
}

const listActiveFactsByCampaign = `-- name: ListActiveFactsByCampaign :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at, player_known
FROM world_facts
WHERE campaign_id = $1
  AND superseded_by IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListActiveFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listActiveFactsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByCampaign = `-- name: ListFactsByCampaign :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at, player_known
FROM world_facts
WHERE campaign_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListFactsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listFactsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByCategory = `-- name: ListFactsByCategory :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at, player_known
FROM world_facts
WHERE campaign_id = $1
  AND category = $2
ORDER BY created_at, id
`

type ListFactsByCategoryParams struct {
	CampaignID pgtype.UUID
	Category   string
}

func (q *Queries) ListFactsByCategory(ctx context.Context, arg ListFactsByCategoryParams) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listFactsByCategory, arg.CampaignID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerKnownFacts = `-- name: ListPlayerKnownFacts :many
SELECT id, campaign_id, fact, category, source, superseded_by, created_at, player_known
FROM world_facts
WHERE campaign_id = $1
  AND player_known = TRUE
  AND superseded_by IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListPlayerKnownFacts(ctx context.Context, campaignID pgtype.UUID) ([]WorldFact, error) {
	rows, err := q.db.Query(ctx, listPlayerKnownFacts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldFact
	for rows.Next() {
		var i WorldFact
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Fact,
			&i.Category,
			&i.Source,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.PlayerKnown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFactPlayerKnown = `-- name: SetFactPlayerKnown :exec
UPDATE world_facts
SET player_known = TRUE
WHERE id = $1
`

func (q *Queries) SetFactPlayerKnown(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setFactPlayerKnown, id)
	return err
}

const supersedeFact = `-- name: SupersedeFact :one
WITH previous_fact AS (
  SELECT world_facts.id, world_facts.campaign_id, world_facts.player_known
  FROM world_facts
  WHERE world_facts.id = $1
    AND world_facts.campaign_id = $2
    AND world_facts.superseded_by IS NULL
  FOR UPDATE
),
new_fact AS (
  INSERT INTO world_facts (
    campaign_id,
    fact,
    category,
    source,
    player_known
  )
  SELECT
    campaign_id,
    $3,
    $4,
    $5,
    player_known OR $6::boolean
  FROM previous_fact
  RETURNING id
),
updated_previous AS (
  UPDATE world_facts
  SET superseded_by = (SELECT id FROM new_fact)
  WHERE world_facts.id = (SELECT id FROM previous_fact)
    AND world_facts.superseded_by IS NULL
  RETURNING id
)
SELECT
  world_facts.id,
  world_facts.campaign_id,
  world_facts.fact,
  world_facts.category,
  world_facts.source,
  world_facts.superseded_by,
  world_facts.created_at,
  world_facts.player_known
FROM world_facts
WHERE world_facts.id = (SELECT id FROM new_fact)
  AND EXISTS (SELECT 1 FROM updated_previous)
`

type SupersedeFactParams struct {
	OldFactID  pgtype.UUID
	CampaignID pgtype.UUID
	Fact       string
	Category   string
	Source     string
	Reveal     bool
}

func (q *Queries) SupersedeFact(ctx context.Context, arg SupersedeFactParams) (WorldFact, error) {
	row := q.db.QueryRow(ctx, supersedeFact,
		arg.OldFactID,
		arg.CampaignID,
		arg.Fact,
		arg.Category,
		arg.Source,
		arg.Reveal,
	)
	var i WorldFact
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Fact,
		&i.Category,
		&i.Source,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.PlayerKnown,
	)
	return i, err
}
